Type: AWS::Cognito::UserPoolClient
Properties:
  ClientName: ${self:custom.resourcesPrefix}-userPoolClient
  GenerateSecret: false
  UserPoolId: { Ref: UserPool }
  ReadAttributes:
    - email
    - name
    - phone_number
    - phone_number_verified
    - email_verified
    - custom:eth_address
    - custom:iban
  WriteAttributes:
    - email
    - name
    - phone_number
    - custom:iban
