name: "TransferTokensSM-${self:service}-${opt:stage}"
definition:
  Comment: Grants free tokens to a new user
  StartAt: TransferTokens
  States:
    ChoiceState:
      Type: Choice
      Choices:
      - Variable: "$.status"
        StringEquals: pending
        Next: WaitTransactionState
      - Not:
          Variable: "$.status"
          StringEquals: pending
        Next: EndState
    TransferTokens:
      Type: Task
      Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-transferTokens"
      Next: WaitTransactionState
    WaitTransactionState:
      Type: Wait
      Seconds: 10
      Next: CheckTransactionState
    CheckTransactionState:
      Type: Task
      Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-checkTransaction"
      Next: ChoiceState
    EndState:
      Type: Pass
      End: true
